### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by tjorim** [jampez77/Ryanair#10]
Version 2023.9.1:
```
Logger: homeassistant.components.sensor
Source: custom_components/ryanair/sensor.py:228
Integration: Sensor (documentation, issues)
First occurred: 15:01:27 (1 occurrences)
Last logged: 15:01:27

Error while setting up ryanair platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ryanair/sensor.py", line 63, in async_setup_entry
    RyanairProfileSensor(profileCoordinator, name, profileDescription),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ryanair/sensor.py", line 228, in __init__
    name=self.coordinator.data["firstName"]
         ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jampez77** [comment]
Fixed in [2023.9.2](https://github.com/jampez77/Ryanair/releases/tag/2023.9.2)
