### ISSUE TITLE
string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by tjorim** [jampez77/Ryanair#27]
Finally made a booking yesterday so I can put this integration to the test 😉

```
Logger: homeassistant.components.image
Source: helpers/entity_platform.py:361
Integration: Image (documentation, issues)
First occurred: 19 December 2023 at 22:00:51 (1 occurrences)
Last logged: 19 December 2023 at 22:00:51

Error while setting up ryanair platform for image
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ryanair/image.py", line 144, in async_setup_entry
    await async_setup_platform(hass, config, async_add_entities)
  File "/config/custom_components/ryanair/image.py", line 100, in async_setup_platform
    flightName = "(" + boardingPass["flight"]["label"] + ") " + \
                       ~~~~~~~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by jampez77** [comment]
Thisa should be fixed with [2024.7.0](https://github.com/jampez77/Ryanair/releases/tag/2024.7.0)
