### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tjorim** [jampez77/Ryanair#8]
Getting the following error when setting up the integration. I currently do not have any upcoming flights.

```
Logger: homeassistant.components.sensor
Source: custom_components/ryanair/sensor.py:117
Integration: Sensor (documentation, issues)
First occurred: 12:39:31 (1 occurrences)
Last logged: 12:39:31

Error while setting up ryanair platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ryanair/sensor.py", line 64, in async_setup_entry
    RyanairFlightsSensor(flightsCoordinator, name, flightsDescription),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ryanair/sensor.py", line 117, in __init__
    self.bookingRef = self.coordinator.data["items"][0]["rawBooking"][
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by jampez77** [comment]
Thanks! I'll have a look at this!

**Comment by jampez77** [comment]
[2023.9.1](https://github.com/jampez77/Ryanair/releases/tag/2023.9.1) should hopefully fix this issue. 

Thanks for raising the bug :)
