### ISSUE TITLE
Unexpected error fetching Ryanair data: 'X-REMEMBERME-TOKEN'

### ISSUE THREAD

**Issue by tjorim** [jampez77/Ryanair#9]
Version 2023.9.1:
```
This error originated from a custom integration.

Logger: custom_components.ryanair.coordinator
Source: custom_components/ryanair/coordinator.py:57
Integration: Ryanair (documentation, issues)
First occurred: 15:01:27 (2 occurrences)
Last logged: 15:01:27

Unexpected error fetching Ryanair data: 'X-REMEMBERME-TOKEN'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ryanair/coordinator.py", line 201, in _async_update_data
    refreshedToken = await refreshToken(self, data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ryanair/coordinator.py", line 57, in refreshToken
    CONF_AUTH_TOKEN: data[X_REMEMBER_ME_TOKEN],
                     ~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'X-REMEMBERME-TOKEN'
```

**Comment by jampez77** [comment]
This is related to [Issue #1](https://github.com/jampez77/Ryanair/issues/1) with regards as to the server session. I'm looking into it.

I will close this one out and track progress in issue #1
